name: surveycam
description: "A camera app for capturing photos with location and geo-tagging features."
publish_to: 'none'

version: 2.0.0+11

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Camera & Media
  camera: ^0.10.5+9
  image: ^4.1.7
  path_provider: ^2.1.2
  photo_view: ^0.14.0
  # Location & Sensors
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  flutter_compass: ^0.8.0

  # State Management
  flutter_riverpod: ^2.4.10

  # Permissions
  permission_handler: ^11.3.0

  # Security & Info
  package_info_plus: ^8.0.0
  safe_device: ^1.1.4

  # Update
  in_app_update: ^4.0.1

  # Storage
  shared_preferences: ^2.2.2

  # UI
  intl: ^0.19.0
  gal: ^2.3.0
  url_launcher: ^6.2.5
  share_plus: ^7.2.1
  sensors_plus: ^4.0.2

  # App Icon
  flutter_launcher_icons: 0.13.1

  exif: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/playstore.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/playstore.png"