allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

def newBuildDir = rootProject.layout.buildDirectory.dir('../../build').get()
rootProject.layout.buildDirectory.set(newBuildDir)
subprojects {
    project.layout.buildDirectory.set(newBuildDir.dir(project.name))
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects {
    def configureAndroidProject = { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (it.hasProperty('compileOptions')) {
                    compileOptions {
                        sourceCompatibility JavaVersion.VERSION_17
                        targetCompatibility JavaVersion.VERSION_17
                    }
                }
                if (it.hasProperty('kotlinOptions')) {
                    kotlinOptions {
                        jvmTarget = '17'
                    }
                }
                if (project.name != 'app' && it.hasProperty('namespace') && it.namespace == null) {
                    it.namespace = project.group
                }
            }
        }
    }

    if (project.state.executed) {
        configureAndroidProject(project)
    } else {
        project.afterEvaluate {
            configureAndroidProject(project)
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
